### PR TITLE
docs: Link to example parsers in the README

### PR DESCRIPTION
**Pull request by Marwes**
As suggested on reddit, having links to different parsers written in combine is a good idea.

These are the parsers I know about that were written in the last half year or so but there might be more.

Please let me know if you want me to remove the link to your respective projects (cc @tailhook, @brennie , @ordian , @dgel and @MaikKlein).

### CODE REVIEW

**Comment by tailhook** [comment]
I also have https://github.com/tailhook/trimmer if you wish to add.

There is also wonderful tantivy project which uses combine to [parse its own query language](https://github.com/tantivy-search/tantivy/blob/1e55189db1afa75e80e49813c91264caaa1b6a1a/src/query/query_parser/query_grammar.rs). (disclaimer: I've neither used tantivy nor it's query language just read of it, and it looks cool)

**Comment by Keats** [comment]
Barely related but I think you should cut out the breaking change list from the README, that's duplicated from the changelog and not in sync anyway.
Looks like all the links after `breaks #` in the changelog are linking to the issues for some reason?

**Comment by Marwes** [comment]
@tailhook Great! Added links to both of those (+ mentat which I just remembered)

@Keats Done. Yep I don't need to list them again there now that I mark breaking changes in the commits. The changelog is auto-generated so I don't really know why the `breaks #` shows up everywhere,,, I should perhaps see if there is a way to avoid it.

**Comment by aidanhs** [comment]
I use combine for lexing - https://github.com/aidanhs/frametool/blob/master/src/lex.rs

(had I discovered combine earlier the whole thing would have been written in it, but I only came across it after desperately searching for some way to resolve some issues I was having with nom)

**Comment by Marwes** [comment]
@aidanhs Added in https://github.com/Marwes/combine/pull/138 :)

**Comment by dgel** [comment]
Huh, I wasn't aware anyone had even seen my advent of code repo. The code in there is fairly rough, but if you think people might find it useful then by all means link it

**Pull request merged**
