### PR TITLE
Translate wiki docs into Japanese, and add a link to README

### PR DESCRIPTION
**Pull request by sadnessOjisan**
Hi, I am a fan of your cool library. I translated some wiki docs into Japanese. Can I publish it as public? And If you’d like, can I add a link in README.md?

### CODE REVIEW

**Comment by gemmaro** [comment]
First of all, I think it's good to have translation, especially for introductory information 🙂

On the other hand, I am concerned about the following two points.

* Updating tediousness - The translation document is written in parallel with quotes of the original text and they have to be manually edited as the original text is updated. Currently, the combine documentation is on the wiki (with the exception of Rustdoc) and anyone can edit it. Therefore, the frequency of updating is not small, and there will be a burden in the future. I recommend po4a management.
* Location where information should be - The content of a pull request is to include a Japanese link in the repository, but I don't know how responsible the author is for the content of the link. So information about the translation itself could be in a wiki instead of a repository.

**Comment by Marwes** [comment]
I think it is fine to have a link to a translation, combine is more or less feature complete so I don't expect documentation to change much anyway and if it still changes to make the translation out of date then hopefully anyone using it will figure that out.

Tests are failing because I used the readme to test that some async parsers work as intended so the number of words it tests against needs to be updated.

**Comment by sadnessOjisan** [comment]
@Marwes Thanks. I was unaware that testing is needed when changing README. I updated the test.

**Comment by sadnessOjisan** [comment]
Oops, failed test? It was successed on my local machine. Check again.

**Pull request merged**
